#!/bin/bash

echo "🐢 Study Coach Logo Download Instructions"
echo "========================================"

echo ""
echo "OPTION 1 - Manual Download (Recommended):"
echo "1. Right-click on your logo image attachment"
echo "2. Select 'Save image as...'"
echo "3. Save as: study_coach_logo.png"
echo "4. Upload to /workspaces/Hackathon-Project/static/"

echo ""
echo "OPTION 2 - VS Code Upload:"
echo "1. Open VS Code file explorer"
echo "2. Navigate to /workspaces/Hackathon-Project/static/"
echo "3. Right-click and select 'Upload...'"
echo "4. Choose your Study Coach logo image"
echo "5. Rename to 'study_coach_logo.png'"

echo ""
echo "OPTION 3 - Terminal Upload (if you have the file locally):"
echo "# Replace 'path/to/your/logo.png' with actual path"
echo "cp path/to/your/logo.png /workspaces/Hackathon-Project/static/study_coach_logo.png"

echo ""
echo "OPTION 4 - Drag and Drop:"
echo "1. Open VS Code file explorer"
echo "2. Navigate to /workspaces/Hackathon-Project/static/"
echo "3. Drag your logo image from your computer"
echo "4. Drop it into the static folder"
echo "5. Rename to 'study_coach_logo.png'"

echo ""
echo "🔍 VERIFICATION COMMAND:"
echo "After saving, run this to verify the logo is properly saved:"
echo ""
echo "ls -la /workspaces/Hackathon-Project/static/study_coach_logo.png"
echo "file /workspaces/Hackathon-Project/static/study_coach_logo.png"

echo ""
echo "✅ CURRENT STATUS:"
ls -la /workspaces/Hackathon-Project/static/study_coach_logo.png 2>/dev/null && echo "Logo file exists!" || echo "Logo file needs to be uploaded"

echo ""
echo "🚀 NEXT STEPS:"
echo "Once the logo is saved, refresh your browser at:"
echo "http://127.0.0.1:5000"
echo ""
echo "The logo will appear on:"
echo "• Header navigation"
echo "• Homepage hero section"
echo "• Login/signup pages"
echo "• AI Assistant sidebar"
